# Generated by Django 4.2.6 on 2024-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='item_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pay',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pay',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
